[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm ci",
  "cd backend && npm ci",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm run start:prod"

